### ISSUE TITLE
Airline / Powerline support?

### ISSUE THREAD

**Issue by rauchg** [pbrisbin/vim-colors-off#1]
First: wow. What a cool idea! Love the light / dark variation, beautiful touch. Thank you for sharing this.
Have you thought about adding support for airline? The colorful status line is a bit startling.

**Comment by pbrisbin** [comment]
> First: wow. What a cool idea! Love the light / dark variation, beautiful touch. Thank you for sharing this.

Thanks very much, I'm glad you enjoy it.

> Have you thought about adding support for airline? The colorful status line is a bit startling.

I can imagine so. Unfortunately, I don't use any of the status line plugins, so I wouldn't add this support myself. But assuming it's just a few more highlight rules, I'd be happy to merge a PR adding whatever's needed.

**Comment by rauchg** [comment]
Makes sense. Thank you. I actually just tried to turn it off and I'm not 100% sure I miss it yet ;P

**Comment by pbrisbin** [comment]
Closing as stale. Feel free to open that PR though!
