### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by qvieth** [pbrisbin/vim-colors-off#11]
![image](https://user-images.githubusercontent.com/71810726/126797668-ef14f684-2462-4352-83bc-14b06a2c05f9.png)

failed to update the plugin

**Comment by pbrisbin** [comment]
I just switched our default branch. Maybe that's why? Please remove and re-add the plugin.

**Comment by qvieth** [comment]
thanks, removing fix the issues, I love this plugin btw

**Comment by pbrisbin** [comment]
Glad to hear it!
