### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lanox** [pbrisbin/vim-colors-off#12]
Hi, 

Is this theme still maintained at all?

**Comment by pbrisbin** [comment]
Yes. I don't use it, or work on it, but am happy to accept PRs.

**Comment by lanox** [comment]
thanks, may I ask what you are using now, as I like this theme and concept of it.

**Comment by pbrisbin** [comment]
Sure, I'm just using the default color scheme. I went on a kick of removing plugins and trying to run with zero configuration where possible, so this got the :axe: in my setup.
