### ISSUE TITLE
Any plans for customization?

### ISSUE THREAD

**Issue by everdimension** [pbrisbin/vim-colors-off#13]
Hi!

First of all, this is an awesome plugin, thank you. I've always loved the no color / minimal color themes and this one is working great so far.

One thing I'd like to be able to do is to customize it just a little. E.g. right now I wish for text color to be just a little more white. This should be a very simple customization, so I wonder is there a way to do that now or do you plan to add support for something like this in the future?

Thanks!

**Comment by pbrisbin** [comment]
Thank you for the kind words. I personally no longer use or work on this color scheme, but I have merged PRs that add similar customization points and would gladly accept one that does what you describe.

I'd also be happy to hand this project off to a more active user of it, if one were willing.
