### ISSUE TITLE
Comment is hidden with colorcolumn

### ISSUE THREAD

**Issue by krehwell** [pbrisbin/vim-colors-off#7]
![image of hidden comment](https://i.imgur.com/2IdI5Pq.png)

any way to improve on this? not really a big thing but maybe it could use a better text color on this?

**Comment by pbrisbin** [comment]
Thanks for the report. I don't use this project anymore, so I'm relying out outside maintainers to make fixes like this.

It should be relatively easy to change the color of the column to something other than the comments. I'm not sure if you can change the comment color _when overlapping with the column_, but it wouldn't surprise me if it's possible.

**Comment by krehwell** [comment]
alright, I submit a pull request for it https://github.com/pbrisbin/vim-colors-off/pull/8

**Comment by pbrisbin** [comment]
Fixed by #8
