### ISSUE TITLE
Are you intersested in adding colors for git diff changes?

### ISSUE THREAD

**Issue by krehwell** [pbrisbin/vim-colors-off#9]
I am adding this colors for ease of navigation in my theme. I just wonder if it would be better if this is just merged in the plugin itself.

here:
![image of git vim-off](https://i.imgur.com/ru8p1Ep.png)

**Comment by pbrisbin** [comment]
Hmm, I could be OK with that. The README says that diff is one view where I conceded that some coloring was required, so this is in line with that. That said, these symbols seem easily distinguishable by shape, so I'm not sure it meets the "required" bar for me.

What does it look like now? Have you tried greyscale, maybe `-` same as comments and `+` same as text?

**Comment by krehwell** [comment]
maybe more into personal preference where it is easier for me to distinguish between color rather than shape. I actually has a suggestion too to add fzf/telescope/ctrl-p word match color during fuzzy search. 

basically I add color to some feature because ease of navigation/distinguish since I used this color scheme as my default theme.

grayscale does not help much in my eyes to detect what actually git does since there are three types of shapes git uses.

**Comment by pbrisbin** [comment]
Could you implement these colors behind a flag, something like `g:colors-off-a-little`?

I'm trying to keep the spirit of the "off" theme, which is the idea that colors are more of a distraction than help (for some). Any added color works against that. I understand that asking you to fork a new theme stinks, so I'm wondering if a flag is a good compromise.

**Comment by krehwell** [comment]
aa I see. I don't really get used to with vim script but I might try it to make a flag

**Comment by pbrisbin** [comment]
Closed by #10
